### ISSUE TITLE
send redis data to zabbix3.0.9 response success but all be failed

### ISSUE THREAD

**Issue by jinjin123** [vTNT/zbx_redis_template#1]
{'aof_rewrite_in_progress': 0, 'total_connections_received': 14, 'used_cpu_sys_children': 0.0, 'repl_backlog_active': 0, 'run_id': 'b58092a31782b77635d7830d7c0720267a4a0060', 'rejected_connections': 83, 'redis_build_id': '672aed6eb816ad6c', 'used_memory_peak_human': '793.84K', 'pubsub_patterns': 0, 'redis_mode': 'standalone', 'connected_slaves': 0, 'uptime_in_days': 0, 'multiplexing_api': 'epoll', 'lru_clock': 2362541, 'redis_version': '3.2.3', 'redis_git_sha1': 0, 'sync_partial_ok': 0, 'migrate_cached_sockets': 0, 'executable': '/etc/zabbix/etc/redis-server', 'gcc_version': '4.8.5', 'connected_clients': 1, 'used_memory_lua_human': '37.00K', 'used_memory': 812888, 'tcp_port': 6379, 'maxmemory': 0, 'used_cpu_user_children': 0.0, 'repl_backlog_first_byte_offset': 0, 'rdb_current_bgsave_time_sec': -1, 'pubsub_channels': 0, 'used_cpu_user': 0.69, 'total_system_memory_human': '1.79G', 'instantaneous_ops_per_sec': 0, 'rdb_last_save_time': 1512309357, 'total_commands_processed': 23, 'aof_last_write_status': 'ok', 'role': 'master', 'cluster_enabled': 0, 'aof_rewrite_scheduled': 0, 'sync_partial_err': 0, 'used_memory_rss': 2486272, 'hz': 10, 'sync_full': 0, 'aof_enabled': 0, 'config_file': '', 'used_cpu_sys': 2.1, 'rdb_last_bgsave_status': 'ok', 'instantaneous_output_kbps': 0.0, 'latest_fork_usec': 0, 'maxmemory_policy': 'noeviction', 'aof_last_bgrewrite_status': 'ok', 'maxmemory_human': '0B', 'aof_last_rewrite_time_sec': -1, 'used_memory_human': '793.84K', 'loading': 0, 'blocked_clients': 0, 'process_id': 58395, 'rdb_bgsave_in_progress': 0, 'repl_backlog_histlen': 0, 'client_biggest_input_buf': 0, 'aof_current_rewrite_time_sec': -1, 'arch_bits': 64, 'master_repl_offset': 0, 'used_memory_lua': 37888, 'rdb_last_bgsave_time_sec': -1, 'expired_keys': 0, 'mem_fragmentation_ratio': 3.06, 'total_net_input_bytes': 625, 'evicted_keys': 0, 'keyspace_misses': 0, 'total_system_memory': 1922818048, 'repl_backlog_size': 1048576, 'instantaneous_input_kbps': 0.0, 'client_longest_output_list': 0, 'mem_allocator': 'jemalloc-3.6.0', 'total_net_output_bytes': 25757, 'used_memory_peak': 812888, 'uptime_in_seconds': 2624, 'rdb_changes_since_last_save': 0, 'redis_git_dirty': 0, 'os': 'Linux 3.10.0-229.el7.x86_64 x86_4', 'used_memory_rss_human': '2.37M', 'keyspace_hits': 0}
{"response":"success","info":"processed: 0; failed: 83; total: 83; seconds spent: 0.000502"}
{u'info': u'processed: 0; failed: 83; total: 83; seconds spent: 0.000502', u'response': u'success'}
@vTNT  guys , can you help me?  my zabbix server and agent is  3.0.9 ,and  zabbix server just import the  redis template  not to do other opeations?  like  setting  item key  so on ...

**Comment by jinjin123** [comment]
I saw the template had set key.
"""
 [Metric('localhost', 'redis[aof_rewrite_in_progress]', 0), Metric('localhost', 'redis[total_connections_received]', 16), Metric('localhost', 'redis[used_cpu_sys_children]', 0.0), Metric('localhost', 'redis[repl_backlog_active]', 0), Metric('localhost', 'redis[run_id]', 'b58092a31782b77635d7830d7c0720267a4a0060'), Metric('localhost', 'redis[rejected_connections]', 98), Metric('localhost', 'redis[redis_build_id]', '672aed6eb816ad6c'), Metric('localhost', 'redis[used_memory_peak_human]', '793.84K'), Metric('localhost', 'redis[pubsub_patterns]', 0), Metric('localhost', 'redis[redis_mode]', 'standalone'), Metric('localhost', 'redis[connected_slaves]', 0), Metric('localhost', 'redis[uptime_in_days]', 0), Metric('localhost', 'redis[multiplexing_api]', 'epoll'), Metric('localhost', 'redis[lru_clock]', 2363024), Metric('localhost', 'redis[redis_version]', '3.2.3'), Metric('localhost', 'redis[redis_git_sha1]', 0), Metric('localhost', 'redis[sync_partial_ok]', 0), Metric('localhost', 'redis[migrate_cached_sockets]', 0), Metric('localhost', 'redis[executable]', '/etc/zabbix/etc/redis-server'), Metric('localhost', 'redis[gcc_version]', '4.8.5'), Metric('localhost', 'redis[connected_clients]', 1), Metric('localhost', 'redis[used_memory_lua_human]', '37.00K'), Metric('localhost', 'redis[used_memory]', 812888), Metric('localhost', 'redis[tcp_port]', 6379), Metric('localhost', 'redis[maxmemory]', 0), Metric('localhost', 'redis[used_cpu_user_children]', 0.0), Metric('localhost', 'redis[repl_backlog_first_byte_offset]', 0), Metric('localhost', 'redis[rdb_current_bgsave_time_sec]', -1), Metric('localhost', 'redis[pubsub_channels]', 0), Metric('localhost', 'redis[used_cpu_user]', 0.83), Metric('localhost', 'redis[total_system_memory_human]', '1.79G'), Metric('localhost', 'redis[instantaneous_ops_per_sec]', 0), Metric('localhost', 'redis[rdb_last_save_time]', 1512309357), Metric('localhost', 'redis[total_commands_processed]', 27), Metric('localhost', 'redis[aof_last_write_status]', 'ok'), Metric('localhost', 'redis[role]', 'master'), Metric('localhost', 'redis[cluster_enabled]', 0), Metric('localhost', 'redis[aof_rewrite_scheduled]', 0), Metric('localhost', 'redis[sync_partial_err]', 0), Metric('localhost', 'redis[used_memory_rss]', 2486272), Metric('localhost', 'redis[hz]', 10), Metric('localhost', 'redis[sync_full]', 0), Metric('localhost', 'redis[aof_enabled]', 0), Metric('localhost', 'redis[config_file]', ''), Metric('localhost', 'redis[used_cpu_sys]', 2.48), Metric('localhost', 'redis[rdb_last_bgsave_status]', 'ok'), Metric('localhost', 'redis[instantaneous_output_kbps]', 0.0), Metric('localhost', 'redis[latest_fork_usec]', 0), Metric('localhost', 'redis[maxmemory_policy]', 'noeviction'), Metric('localhost', 'redis[aof_last_bgrewrite_status]', 'ok'), Metric('localhost', 'redis[maxmemory_human]', '0B'), Metric('localhost', 'redis[aof_last_rewrite_time_sec]', -1), Metric('localhost', 'redis[used_memory_human]', '793.84K'), Metric('localhost', 'redis[loading]', 0), Metric('localhost', 'redis[blocked_clients]', 0), Metric('localhost', 'redis[process_id]', 58395), Metric('localhost', 'redis[rdb_bgsave_in_progress]', 0), Metric('localhost', 'redis[repl_backlog_histlen]', 0), Metric('localhost', 'redis[client_biggest_input_buf]', 0), Metric('localhost', 'redis[aof_current_rewrite_time_sec]', -1), Metric('localhost', 'redis[arch_bits]', 64), Metric('localhost', 'redis[master_repl_offset]', 0), Metric('localhost', 'redis[used_memory_lua]', 37888), Metric('localhost', 'redis[rdb_last_bgsave_time_sec]', -1), Metric('localhost', 'redis[expired_keys]', 0), Metric('localhost', 'redis[mem_fragmentation_ratio]', 3.06), Metric('localhost', 'redis[total_net_input_bytes]', 731), Metric('localhost', 'redis[evicted_keys]', 0), Metric('localhost', 'redis[keyspace_misses]', 0), Metric('localhost', 'redis[total_system_memory]', 1922818048), Metric('localhost', 'redis[repl_backlog_size]', 1048576), Metric('localhost', 'redis[instantaneous_input_kbps]', 0.0), Metric('localhost', 'redis[client_longest_output_list]', 0), Metric('localhost', 'redis[mem_allocator]', 'jemalloc-3.6.0'), Metric('localhost', 'redis[total_net_output_bytes]', 30051), Metric('localhost', 'redis[used_memory_peak]', 812888), Metric('localhost', 'redis[uptime_in_seconds]', 3107), Metric('localhost', 'redis[rdb_changes_since_last_save]', 0), Metric('localhost', 'redis[redis_git_dirty]', 0), Metric('localhost', 'redis[os]', 'Linux 3.10.0-229.el7.x86_64 x86_64'), Metric('localhost', 'redis[used_memory_rss_human]', '2.37M'), Metric('localhost', 'redis[keyspace_hits]', 0)]"""

**Comment by vTNT** [comment]
I just tested in 3.0 environment。 this template it can work. so u need check u opeations.
1. import the xml file

**Comment by vTNT** [comment]
I just tested in 3.0.13 environment.  it can import and collect redis data sucessful.

**Comment by jinjin123** [comment]
@vTNT  ok ,thanks , I used shell  script to fixed this  issue.
